### ISSUE TITLE
File structure for Ruby extension

### ISSUE THREAD

**Issue by abinashmeher999** [sympy/symengine#413]
Since python wrappers are outside src. I was wondering if the ruby wrappers should go inside src as done in [FLANN](https://github.com/mariusmuja/flann/tree/master/src/ruby). It would be better to have all the wrappers at a common place. Also, some functions have already been covered with extern in cwrapper.h which is in src. Thought it would better to discuss it here first.

**Comment by certik** [comment]
Very good question @abinashmeher999. I was wondering what the best way is. 

We currently allow to use `setup.py` to install both the library and the Python wrappers using cmake. Also one can import csympy directly from the build directory (we had to hack distutils for that, it's not ideal).

But I think it makes more sense to rather just install the Python and Ruby wrappers where the user wants them, and cmake would first install the csympy C++ library. Then the Python wrappers would be installed using `setup.py` and distutils, and Ruby wrappers using `Rakefile`. That way, native tools are used for Python and Ruby, and all the wrappers have to do is to link with the proper .so or .a or .dylib, just like with any other library. We can still hook this up into cmake, so that cmake invokes the `setup.py` or `Rakefile`.

So we can do `src/ruby` and `src/python`. And later add `src/matlab`, `src/R`, `src/mathematica`, ...

/cc @pbrady.

**Comment by abinashmeher999** [comment]
@certik I agree. The new structure makes much more sense and would be very easy for the future contributors to see and understand the project structure.
>But I think it makes more sense to rather just install the Python and Ruby wrappers where the user wants them, and cmake would first install the csympy C++ library. Then the Python wrappers would be installed using `setup.py` and distutils, and Ruby wrappers using `Rakefile`. That way, native tools are used for Python and Ruby, and all the wrappers have to do is to link with the proper .so or .a or .dylib, just like with any other library. We can still hook this up into cmake, so that cmake invokes the `setup.py` or `Rakefile`.

I have a question here. Did you mean the user builds the C++ library first and separately builds the wrappers manually? It would be a lot easier if we allow the wrappers to be installed by passing appropriate flags to cmake like `-DWITH_PYTHON=yes -DWITH_RUBY=yes`. I think this is what you meant with hooking it up into cmake. I am not familiar if we can invoke `rake` from cmake.

I have read a little bit about distutils. They are used to distribute python libraries through pip. If we are planning to make the python libraries available to be installed by pip, it would be convenient to put the ruby wrappers in a gem. Isn't it? That way we can make the Ruby wrappers available by `gem install` too!

**Comment by certik** [comment]
Yes, that's what I meant. Rake can be called from cmake as well.

Yes, csympy already works with pip and we should make it work with gem as
well.

**Comment by Sumith1896** [comment]
Is this issue figured out? 
The first PR regarding this got merged, just checking.

**Comment by abinashmeher999** [comment]
Yup. I think this can be closed now since the ruby file structure has been figured out.
